service: project-name-generator

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'

  environment:
    FOO: BAR
    FUNCTION_PREFIX: ${self:service}-${self:provider.stage}

plugins:
  - serverless-bundle
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

package:
  individually: true
  excludeDevDependencies: false

functions:
  entrypoint:
    handler: src/handlers/entrypoint.handler
    events:
      - http:
          path: 'generate'
          method: GET
