service: project-name-generator

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-southeast-1

  tracing:
    apiGateway: true
    lambda: true

  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: '*'

  environment:
    REGION: ${self:provider.region}
    FUNCTION_PREFIX: ${self:service}-${self:provider.stage}

plugins:
  - serverless-bundle
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

package:
  excludeDevDependencies: false

functions: ${file(./src/resources/functions.js)}
